apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-basic
        image: guizerajs/web-basic:2.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-basic
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer