name: CD-CD

on:
  push:
    branches: ["main"]
    
jobs:
  Build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Autenticação no Azure Registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PASS}}
          registry: ${{secrets.DOCKER_REGISTRY_DOMAIN}}
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v4.0.0
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            afrocrownregistry.azurecr.io/web-basic:v1
            afrocrownregistry.azurecr.io/web-basic:latest
