name: CD-CD

on:
  push:
    branches: ["main"]
    
jobs:
  Build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Autenticação no Azure Registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PASS}}
          registry: ${{secrets.DOCKER_REGISTRY_DOMAIN}}
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v4.0.0
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            afrocrownregistry.azurecr.io/web-basic:v${{github.run_number}}
            afrocrownregistry.azurecr.io/web-basic:latest
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Autenticação no Azure Registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PASS}}
          registry: ${{secrets.DOCKER_REGISTRY_DOMAIN}}
      - name: Definindo o context
        uses: Azure/k8s-set-context@v3.0
        with: 
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with: 
          images: afrocrownregistry.azurecr.io/web-basic:v${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
        
      
      
      
